/*
 * The Helcim API
 * This API covers publicly accessible merchant actions
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CaptureRequest
 */
public class CaptureRequestTest {
    private final CaptureRequest model = new CaptureRequest();

    /**
     * Model tests for CaptureRequest
     */
    @Test
    public void testCaptureRequest() {
        // TODO: test CaptureRequest
    }

    /**
     * Test the property 'preAuthTransactionId'
     */
    @Test
    public void preAuthTransactionIdTest() {
        // TODO: test preAuthTransactionId
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'ipAddress'
     */
    @Test
    public void ipAddressTest() {
        // TODO: test ipAddress
    }

    /**
     * Test the property 'ecommerce'
     */
    @Test
    public void ecommerceTest() {
        // TODO: test ecommerce
    }

}
