/*
 * The Helcim API
 * This API covers publicly accessible merchant actions
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CardResponse
 */
public class CardResponseTest {
    private final CardResponse model = new CardResponse();

    /**
     * Model tests for CardResponse
     */
    @Test
    public void testCardResponse() {
        // TODO: test CardResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'cardToken'
     */
    @Test
    public void cardTokenTest() {
        // TODO: test cardToken
    }

    /**
     * Test the property 'dateCreated'
     */
    @Test
    public void dateCreatedTest() {
        // TODO: test dateCreated
    }

    /**
     * Test the property 'dateUpdated'
     */
    @Test
    public void dateUpdatedTest() {
        // TODO: test dateUpdated
    }

    /**
     * Test the property 'cardHolderName'
     */
    @Test
    public void cardHolderNameTest() {
        // TODO: test cardHolderName
    }

    /**
     * Test the property 'cardF6L4'
     */
    @Test
    public void cardF6L4Test() {
        // TODO: test cardF6L4
    }

    /**
     * Test the property 'cardExpiry'
     */
    @Test
    public void cardExpiryTest() {
        // TODO: test cardExpiry
    }

    /**
     * Test the property 'cardCVV'
     */
    @Test
    public void cardCVVTest() {
        // TODO: test cardCVV
    }

}
