/*
 * The Helcim API
 * This API covers publicly accessible merchant actions
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CardBatch
 */
public class CardBatchTest {
    private final CardBatch model = new CardBatch();

    /**
     * Model tests for CardBatch
     */
    @Test
    public void testCardBatch() {
        // TODO: test CardBatch
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'dateCreated'
     */
    @Test
    public void dateCreatedTest() {
        // TODO: test dateCreated
    }

    /**
     * Test the property 'dateUpdated'
     */
    @Test
    public void dateUpdatedTest() {
        // TODO: test dateUpdated
    }

    /**
     * Test the property 'dateClosed'
     */
    @Test
    public void dateClosedTest() {
        // TODO: test dateClosed
    }

    /**
     * Test the property 'closed'
     */
    @Test
    public void closedTest() {
        // TODO: test closed
    }

    /**
     * Test the property 'terminalId'
     */
    @Test
    public void terminalIdTest() {
        // TODO: test terminalId
    }

    /**
     * Test the property 'batchNumber'
     */
    @Test
    public void batchNumberTest() {
        // TODO: test batchNumber
    }

    /**
     * Test the property 'netSales'
     */
    @Test
    public void netSalesTest() {
        // TODO: test netSales
    }

    /**
     * Test the property 'totalSales'
     */
    @Test
    public void totalSalesTest() {
        // TODO: test totalSales
    }

    /**
     * Test the property 'totalRefunds'
     */
    @Test
    public void totalRefundsTest() {
        // TODO: test totalRefunds
    }

    /**
     * Test the property 'totalReversed'
     */
    @Test
    public void totalReversedTest() {
        // TODO: test totalReversed
    }

    /**
     * Test the property 'totalRefundsReversed'
     */
    @Test
    public void totalRefundsReversedTest() {
        // TODO: test totalRefundsReversed
    }

    /**
     * Test the property 'countTotal'
     */
    @Test
    public void countTotalTest() {
        // TODO: test countTotal
    }

    /**
     * Test the property 'countApproved'
     */
    @Test
    public void countApprovedTest() {
        // TODO: test countApproved
    }

    /**
     * Test the property 'countDeclined'
     */
    @Test
    public void countDeclinedTest() {
        // TODO: test countDeclined
    }

}
