/*
 * The Helcim API
 * This API covers publicly accessible merchant actions
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CardToken
 */
public class CardTokenTest {
    private final CardToken model = new CardToken();

    /**
     * Model tests for CardToken
     */
    @Test
    public void testCardToken() {
        // TODO: test CardToken
    }

    /**
     * Test the property 'cardToken'
     */
    @Test
    public void cardTokenTest() {
        // TODO: test cardToken
    }

}
