/*
 * The Helcim API
 * This API covers publicly accessible merchant actions
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GetInvoices200ResponseInner
 */
public class GetInvoices200ResponseInnerTest {
    private final GetInvoices200ResponseInner model = new GetInvoices200ResponseInner();

    /**
     * Model tests for GetInvoices200ResponseInner
     */
    @Test
    public void testGetInvoices200ResponseInner() {
        // TODO: test GetInvoices200ResponseInner
    }

    /**
     * Test the property 'invoiceId'
     */
    @Test
    public void invoiceIdTest() {
        // TODO: test invoiceId
    }

    /**
     * Test the property 'invoiceNumber'
     */
    @Test
    public void invoiceNumberTest() {
        // TODO: test invoiceNumber
    }

    /**
     * Test the property 'tipAmount'
     */
    @Test
    public void tipAmountTest() {
        // TODO: test tipAmount
    }

    /**
     * Test the property 'depositAmount'
     */
    @Test
    public void depositAmountTest() {
        // TODO: test depositAmount
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'dateCreated'
     */
    @Test
    public void dateCreatedTest() {
        // TODO: test dateCreated
    }

    /**
     * Test the property 'dateUpdated'
     */
    @Test
    public void dateUpdatedTest() {
        // TODO: test dateUpdated
    }

    /**
     * Test the property 'datePaid'
     */
    @Test
    public void datePaidTest() {
        // TODO: test datePaid
    }

    /**
     * Test the property 'dateIssued'
     */
    @Test
    public void dateIssuedTest() {
        // TODO: test dateIssued
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    public void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'convenienceFee'
     */
    @Test
    public void convenienceFeeTest() {
        // TODO: test convenienceFee
    }

}
