/*
 * The Helcim API
 * This API covers publicly accessible merchant actions
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RefundRequest1
 */
public class RefundRequest1Test {
    private final RefundRequest1 model = new RefundRequest1();

    /**
     * Model tests for RefundRequest1
     */
    @Test
    public void testRefundRequest1() {
        // TODO: test RefundRequest1
    }

    /**
     * Test the property 'cardTransactionId'
     */
    @Test
    public void cardTransactionIdTest() {
        // TODO: test cardTransactionId
    }

    /**
     * Test the property 'ipAddress'
     */
    @Test
    public void ipAddressTest() {
        // TODO: test ipAddress
    }

    /**
     * Test the property 'ecommerce'
     */
    @Test
    public void ecommerceTest() {
        // TODO: test ecommerce
    }

}
