/*
 * The Helcim API
 * This API covers publicly accessible merchant actions
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SuccessfulPaymentResponse
 */
public class SuccessfulPaymentResponseTest {
    private final SuccessfulPaymentResponse model = new SuccessfulPaymentResponse();

    /**
     * Model tests for SuccessfulPaymentResponse
     */
    @Test
    public void testSuccessfulPaymentResponse() {
        // TODO: test SuccessfulPaymentResponse
    }

    /**
     * Test the property 'transactionId'
     */
    @Test
    public void transactionIdTest() {
        // TODO: test transactionId
    }

    /**
     * Test the property 'cardBatchId'
     */
    @Test
    public void cardBatchIdTest() {
        // TODO: test cardBatchId
    }

    /**
     * Test the property 'dateCreated'
     */
    @Test
    public void dateCreatedTest() {
        // TODO: test dateCreated
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'avsResponse'
     */
    @Test
    public void avsResponseTest() {
        // TODO: test avsResponse
    }

    /**
     * Test the property 'cvvResponse'
     */
    @Test
    public void cvvResponseTest() {
        // TODO: test cvvResponse
    }

    /**
     * Test the property 'approvalCode'
     */
    @Test
    public void approvalCodeTest() {
        // TODO: test approvalCode
    }

    /**
     * Test the property 'cardToken'
     */
    @Test
    public void cardTokenTest() {
        // TODO: test cardToken
    }

    /**
     * Test the property 'cardNumber'
     */
    @Test
    public void cardNumberTest() {
        // TODO: test cardNumber
    }

    /**
     * Test the property 'cardHolderName'
     */
    @Test
    public void cardHolderNameTest() {
        // TODO: test cardHolderName
    }

    /**
     * Test the property 'customerCode'
     */
    @Test
    public void customerCodeTest() {
        // TODO: test customerCode
    }

    /**
     * Test the property 'invoiceNumber'
     */
    @Test
    public void invoiceNumberTest() {
        // TODO: test invoiceNumber
    }

    /**
     * Test the property 'warning'
     */
    @Test
    public void warningTest() {
        // TODO: test warning
    }

}
