/*
 * The Helcim API
 * This API covers publicly accessible merchant actions
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * CheckoutInit200Response
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class CheckoutInit200Response {
  public static final String SERIALIZED_NAME_CHECKOUT_TOKEN = "checkoutToken";
  @SerializedName(SERIALIZED_NAME_CHECKOUT_TOKEN)
  private String checkoutToken;

  public static final String SERIALIZED_NAME_SECRET_TOKEN = "secretToken";
  @SerializedName(SERIALIZED_NAME_SECRET_TOKEN)
  private String secretToken;

  public CheckoutInit200Response() {
  }

  public CheckoutInit200Response checkoutToken(String checkoutToken) {
    
    
    
    
    this.checkoutToken = checkoutToken;
    return this;
  }

   /**
   * The checkout token is used to initialize Helcim Pay
   * @return checkoutToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The checkout token is used to initialize Helcim Pay")

  public String getCheckoutToken() {
    return checkoutToken;
  }


  public void setCheckoutToken(String checkoutToken) {
    
    
    
    this.checkoutToken = checkoutToken;
  }


  public CheckoutInit200Response secretToken(String secretToken) {
    
    
    
    
    this.secretToken = secretToken;
    return this;
  }

   /**
   * The secret token is used to validate the transaction response
   * @return secretToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The secret token is used to validate the transaction response")

  public String getSecretToken() {
    return secretToken;
  }


  public void setSecretToken(String secretToken) {
    
    
    
    this.secretToken = secretToken;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CheckoutInit200Response instance itself
   */
  public CheckoutInit200Response putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CheckoutInit200Response checkoutInit200Response = (CheckoutInit200Response) o;
    return Objects.equals(this.checkoutToken, checkoutInit200Response.checkoutToken) &&
        Objects.equals(this.secretToken, checkoutInit200Response.secretToken)&&
        Objects.equals(this.additionalProperties, checkoutInit200Response.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(checkoutToken, secretToken, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CheckoutInit200Response {\n");
    sb.append("    checkoutToken: ").append(toIndentedString(checkoutToken)).append("\n");
    sb.append("    secretToken: ").append(toIndentedString(secretToken)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("checkoutToken");
    openapiFields.add("secretToken");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CheckoutInit200Response
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CheckoutInit200Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CheckoutInit200Response is not found in the empty JSON string", CheckoutInit200Response.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("checkoutToken") != null && !jsonObj.get("checkoutToken").isJsonNull()) && !jsonObj.get("checkoutToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `checkoutToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("checkoutToken").toString()));
      }
      if ((jsonObj.get("secretToken") != null && !jsonObj.get("secretToken").isJsonNull()) && !jsonObj.get("secretToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `secretToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("secretToken").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CheckoutInit200Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CheckoutInit200Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CheckoutInit200Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CheckoutInit200Response.class));

       return (TypeAdapter<T>) new TypeAdapter<CheckoutInit200Response>() {
           @Override
           public void write(JsonWriter out, CheckoutInit200Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public CheckoutInit200Response read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             CheckoutInit200Response instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CheckoutInit200Response given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CheckoutInit200Response
  * @throws IOException if the JSON string is invalid with respect to CheckoutInit200Response
  */
  public static CheckoutInit200Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CheckoutInit200Response.class);
  }

 /**
  * Convert an instance of CheckoutInit200Response to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

