/*
 * The Helcim API
 * This API covers publicly accessible merchant actions
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.CardTerminal;
import com.konfigthis.client.model.CardTerminalsRequest;
import com.konfigthis.client.model.FailedPaymentResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CardTerminalApi
 */
@Disabled
public class CardTerminalApiTest {

    private static CardTerminalApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new CardTerminalApi(apiClient);
    }

    /**
     * Get card terminals
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllTest() throws ApiException {
        String currency = null;
        String status = null;
        List<CardTerminal> response = api.getAll()
                .currency(currency)
                .status(status)
                .execute();
        // TODO: test validations
    }

}
