/*
 * The Helcim API
 * This API covers publicly accessible merchant actions
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.CardBatch;
import com.konfigthis.client.model.FailedPaymentResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CardBatchApi
 */
@Disabled
public class CardBatchApiTest {

    private static CardBatchApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new CardBatchApi(apiClient);
    }

    /**
     * Get Card Batches
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAllTest() throws ApiException {
        Double batchNumber = null;
        Double terminalId = null;
        String collectStats = null;
        List<CardBatch> response = api.getAll()
                .batchNumber(batchNumber)
                .terminalId(terminalId)
                .collectStats(collectStats)
                .execute();
        // TODO: test validations
    }

    /**
     * Get Card Batch
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDetailsTest() throws ApiException {
        Integer cardBatchId = null;
        String collectStats = null;
        CardBatch response = api.getDetails(cardBatchId)
                .collectStats(collectStats)
                .execute();
        // TODO: test validations
    }

    /**
     * Settles an Open Card Batch
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void settleBatchTest() throws ApiException {
        Integer cardBatchId = null;
        CardBatch response = api.settleBatch(cardBatchId)
                .execute();
        // TODO: test validations
    }

}
